[env:esp32-s3-devkitc-1]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino

; Speed for the serial monitor
monitor_speed = 115200

; Configuration for S3 native USB (Important for Serial.print to work via USB)
; If your board has two USB ports, use the one marked "USB" or "Native".
build_flags = 
    -D ARDUINO_USB_MODE=1
    -D ARDUINO_USB_CDC_ON_BOOT=1